// <auto-generated />
using System;
using CleanArchIdentityDemo.Infrastructure.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchIdentityDemo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107223439_LogicaTablasActivoInactivo")]
    partial class LogicaTablasActivoInactivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.AccesoModulo", b =>
                {
                    b.Property<int>("IdAccesoModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccesoModulo"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdAccesoModulo");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AccesosModulo", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.AuditoriaAccion", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaAcciones", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContrato");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Contratos", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.CostoEjecutado", b =>
                {
                    b.Property<int>("IdCosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCosto"));

                    b.Property<string>("CategoriaGasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaComprobante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCosto");

                    b.HasIndex("ProyectoId");

                    b.ToTable("CostosEjecutados", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.DevolucionMaterial", b =>
                {
                    b.Property<int>("IdDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDevolucion"));

                    b.Property<int>("CantidadDevuelta")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaterialProyectoId")
                        .HasColumnType("int");

                    b.HasKey("IdDevolucion");

                    b.HasIndex("MaterialProyectoId");

                    b.ToTable("DevolucionesMaterial", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CategoriaDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivoOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreBlob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaBlobCompleta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubidoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalVersiones")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VersionActual")
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("IdDocumento");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("SubidoPor");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.DocumentoVersion", b =>
                {
                    b.Property<int>("IdVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVersion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsVersionActual")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreBlob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NumeroVersion")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("RutaBlobCompleta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubidoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVersion");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("SubidoPor");

                    b.ToTable("DocumentoVersiones", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.EstadoProyecto", b =>
                {
                    b.Property<int>("IdEstadoProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoProyecto"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstadoProyecto");

                    b.ToTable("EstadosProyecto", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.HoraLaboral", b =>
                {
                    b.Property<int>("IdHoraLaboral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoraLaboral"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonalProyectoId")
                        .HasColumnType("int");

                    b.HasKey("IdHoraLaboral");

                    b.HasIndex("PersonalProyectoId");

                    b.ToTable("HorasLaborales", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncidente"));

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("IdIncidente");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Incidentes", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.MantenimientoMaquinaria", b =>
                {
                    b.Property<int>("IdMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMantenimiento"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaquinariaId")
                        .HasColumnType("int");

                    b.HasKey("IdMantenimiento");

                    b.HasIndex("MaquinariaId");

                    b.ToTable("MantenimientosMaquinaria", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Maquinaria", b =>
                {
                    b.Property<int>("IdMaquinaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaquinaria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoMaquinaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMaquinaria");

                    b.ToTable("Maquinarias", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.MaquinariaProyecto", b =>
                {
                    b.Property<int>("IdMaquinariaProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaquinariaProyecto"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaquinariaId")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("IdMaquinariaProyecto");

                    b.HasIndex("MaquinariaId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("MaquinariaProyecto", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMaterial");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Materiales", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.MaterialProyecto", b =>
                {
                    b.Property<int>("IdMaterialProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterialProyecto"));

                    b.Property<int>("CantidadEnObra")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("IdMaterialProyecto");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("MaterialesProyecto", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.MaterialSolicitado", b =>
                {
                    b.Property<int>("IdMaterialSolicitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterialSolicitado"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.HasKey("IdMaterialSolicitado");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("MaterialesSolicitados", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.NotaAvance", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNota"));

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Destacada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNota")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("IdNota");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ProyectoId");

                    b.ToTable("NotasAvance", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.PagoProveedor", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreDocumentoSubido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaComprobante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPago");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("PagosProveedores", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.PersonalProyecto", b =>
                {
                    b.Property<int>("IdPersonalProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonalProyecto"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPersonalProyecto");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PersonalProyecto", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProveedor");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Proyecto", b =>
                {
                    b.Property<int>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProyecto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoProyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoProyectoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinalPropuesta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProyecto");

                    b.HasIndex("EstadoProyectoId");

                    b.ToTable("Proyectos", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.SolicitudMaterial", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("EstadoSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacionesBodeguero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("ProyectoId");

                    b.ToTable("SolicitudesMaterial", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarea"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFinalEsperada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioEsperada")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreTarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PorcentajeAvance")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("IdTarea");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.AccesoModulo", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.AuditoriaAccion", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("Contratos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.CostoEjecutado", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("CostosEjecutados")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.DevolucionMaterial", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.MaterialProyecto", "MaterialProyecto")
                        .WithMany("Devoluciones")
                        .HasForeignKey("MaterialProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialProyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Documento", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("Documentos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SubidoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.DocumentoVersion", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Documento", "Documento")
                        .WithMany("Versiones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SubidoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.HoraLaboral", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.PersonalProyecto", "PersonalProyecto")
                        .WithMany("HorasLaborales")
                        .HasForeignKey("PersonalProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalProyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("Incidentes")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.MantenimientoMaquinaria", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Maquinaria", "Maquinaria")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("MaquinariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquinaria");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.MaquinariaProyecto", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Maquinaria", "Maquinaria")
                        .WithMany("ProyectosAsignados")
                        .HasForeignKey("MaquinariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("MaquinariasProyecto")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquinaria");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Material", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Materiales")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.MaterialProyecto", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Material", "Material")
                        .WithMany("MaterialesProyecto")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("MaterialesProyecto")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.MaterialSolicitado", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Material", "Material")
                        .WithMany("MaterialesSolicitados")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.SolicitudMaterial", "SolicitudMaterial")
                        .WithMany("MaterialesSolicitados")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("SolicitudMaterial");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.NotaAvance", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("NotasAvance")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.PagoProveedor", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("PagosProveedores")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("PagosProveedores")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.PersonalProyecto", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("PersonalProyectos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Proyecto", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.EstadoProyecto", "EstadoProyecto")
                        .WithMany("Proyectos")
                        .HasForeignKey("EstadoProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoProyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.SolicitudMaterial", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("SolicitudesMaterial")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Tarea", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CleanArchIdentityDemo.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Documento", b =>
                {
                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.EstadoProyecto", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Maquinaria", b =>
                {
                    b.Navigation("Mantenimientos");

                    b.Navigation("ProyectosAsignados");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Material", b =>
                {
                    b.Navigation("MaterialesProyecto");

                    b.Navigation("MaterialesSolicitados");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.MaterialProyecto", b =>
                {
                    b.Navigation("Devoluciones");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.PersonalProyecto", b =>
                {
                    b.Navigation("HorasLaborales");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("PagosProveedores");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.Proyecto", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("CostosEjecutados");

                    b.Navigation("Documentos");

                    b.Navigation("Incidentes");

                    b.Navigation("MaquinariasProyecto");

                    b.Navigation("MaterialesProyecto");

                    b.Navigation("NotasAvance");

                    b.Navigation("PagosProveedores");

                    b.Navigation("PersonalProyectos");

                    b.Navigation("SolicitudesMaterial");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("CleanArchIdentityDemo.Domain.Entities.SolicitudMaterial", b =>
                {
                    b.Navigation("MaterialesSolicitados");
                });
#pragma warning restore 612, 618
        }
    }
}
